title: MARK ADRIAN CALMA
logo: assets/Untitled design (16).png
description: Data Analyst skilled in SQL, Power BI, and Excel, delivering insights for business growth.
show_downloads: false
theme: jekyll-theme-minimal
